### ISSUE TITLE
running falcon and falcon_unzip with HiFi reads

### ISSUE THREAD

**Issue by sjin09** [gconcepcion/pb-assembly#5]
To whom it may concern,

I am attempting to run falcon and falcon_unzip through pb-assembly. The fasta header of CCS/HiFi reads does not seem to be compatible with the daligner that is installed together with pb-assembly. I was wondering when PacBio might push an update for pb-assembly that would run with the HiFI reads.

Regards,
Sangjin Lee

**Comment by skingan** [comment]
Hi Sangjin Lee, We have recently updated pb-assembly to support HiFi data. Are you running the latest code? You can update your environment by running "conda update --all" after you have loaded pb-assembly. If you continue to have problems please file issues here:

https://github.com/PacificBiosciences/pbbioconda/issues

Details on FALCON Unzip for HiFi:

https://github.com/PacificBiosciences/pbbioconda/wiki/HiFi-:--FALCON-Unzip3-User-Guide
